---
- name: all vpcs
  ec2_vpc_net_info:
    region: "{{region}}"
    filters:
      "tag:Name": Ansible VPC
  register: all_vpc

- name: all vpc route tables
  ec2_vpc_route_table_info:
    region: "{{region}}"
    filters:
      "tag:name": my-rt
  register: all_vpc_route_table

- name: Get All security groups
  ec2_group_info:
    region: "{{region}}"
    filters:
      "tag:Name": ansible-sg
  register: all_security_groups

- name: delete public subnet 1
  ec2_vpc_subnet:
    vpc_id: "{{ item.vpc_id }}"
    cidr: "{{ subnet1_cidr }}"
    state: absent
    region: "{{region}}"
  with_items: "{{ all_vpc.vpcs }}"
  when: all_vpc.vpcs is defined

- name: delete public subnet 2
  ec2_vpc_subnet:
    vpc_id: "{{ item.vpc_id }}"
    cidr: "{{ subnet2_cidr }}"
    state: absent
    region: "{{region}}"
  with_items: "{{ all_vpc.vpcs }}"
  when: all_vpc.vpcs is defined

- name: delete public subnet 3
  ec2_vpc_subnet:
    vpc_id: "{{ item.vpc_id }}"
    cidr: "{{ subnet3_cidr }}"
    state: absent
    region: "{{region}}"
  with_items: "{{ all_vpc.vpcs }}"
  when: all_vpc.vpcs is defined

- name: delete Internet Gateway
  ec2_vpc_igw:
    vpc_id: "{{ item.vpc_id }}"
    state: absent
    region: "{{region}}"
  with_items: "{{ all_vpc.vpcs }}"
  when: all_vpc.vpcs is defined

- debug:
    var:
      all_security_groups

- name: "Delete group by its id"
  ec2_group:
    region: "{{ region }}"
    group_id: "{{ item.group_id }}"
    state: absent
  with_items: "{{ all_security_groups.security_groups }}"
  when: all_security_groups.security_groups is defined
  
- debug:
    var:
      all_vpc_route_table

- name: delete non-main route table
  ec2_vpc_route_table:
    vpc_id: "{{ all_vpc.vpcs[0]['vpc_id'] }}"
    region: "{{ region }}"
    route_table_id: "{{ item.id  }}"
    lookup: id
    state: absent
  with_items: "{{ all_vpc_route_table.route_tables }}"
  
- name: delete vpc
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    region: "{{region}}"
    cidr_block: "{{ vpc_cidr }}"
    state: absent
  when: all_vpc.vpcs is defined
