---
# tasks file for install-jenkins
  - name: install dependencies
    apt:
      update_cache: yes
      name: "{{ package }}"
      state: present
    vars:
      package:
      - wget
      - openjdk-8-jdk
      - git
  
  - name: Import Jenkins Repo GPG key
    apt_key:
      state: present
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key

  - name: ensure the repository is configured
    apt_repository:
      repo: deb https://pkg.jenkins.io/debian-stable binary/
      state: present
  
  - name: install Jenkins
    yum:
      name: jenkins
      state: present

  - name: Temporarily Stop Jenkins
    service: 
      name: jenkins 
      state: stopped
  
  - name: Modify user shell
    user:
      name: jenkins
      shell: /bin/bash
  

  - name: Start Jenkins
    service:
      name: jenkins
      state: started
      enabled: yes

  - name: Wait until Jenkins is up
    shell: result_first=1; while [[ $result_first != 0 ]]; do if [[ `grep 'Jenkins is fully up and running' /var/log/jenkins/jenkins.log` ]];then result_first=0;else sleep 4;fi;done
    register: result
    until: result.rc == 0